### ISSUE TITLE
Does not make parallel build support explicit

### ISSUE THREAD

**Issue by t-b** [sphinx-contrib/youtube#29]
When doing a parallel build with `sphinx-build -j auto ...` I get 

```
WARNING: the sphinxembeddedvideos.youtube extension does not declare if it is safe for parallel reading,
assuming it isn't - please ask the extension author to check and make it explicit
```

This is with sphinx 4.4. Does it support parallel builds? See also https://www.sphinx-doc.org/en/master/extdev/index.html?highlight=parallel_read_safe#extension-metadata.

**Comment by dham** [comment]
I have to confess that I don't know the answer to this one. Are we parallel safe? I don't think we're doing anything that wouldn't be but I also really know what the constraints are in this case.

**Comment by t-b** [comment]
The posted link from me has:

```
The parallel-read-safe extension must satisfy the following conditions:

    The core logic of the extension is parallelly executable during the reading phase.

    It has event handlers for [env-merge-info](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-merge-info) and [env-purge-doc](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-purge-doc) events if it stores data to the build environment object (env) during the reading phase.
```

Does that help?

**Comment by dham** [comment]
I read that but I didn't really understand it. I *think* the exension doesn't modify any shared state during read so I *think* it's probably parallel-safe. However I don't really know how I would go about checking that. I am slightly nervous about publishing metadata saying we're parallel-safe on without really knowing.

Since you have a parallel build set up, can you at least test whether your build works with a version of this plugin that advertises itself as parallel-safe?

**Comment by t-b** [comment]
I've hacked support into the extension [1] and it does still build here.

[1]: https://github.com/t-b/youtube/tree/mark-extension-as-parallel-read-write

**Comment by chrisjsewell** [comment]
Heya, FYI I believe it may not be parallel safe, because of the use of `env.remote_images` here: https://github.com/sphinx-contrib/youtube/blob/e12497621d1ed3a5ad357c8db8ab67a9799f9a20/sphinxcontrib/youtube/utils.py#L137

This will not be propagated when you merge the environments from parallel builds.
So you need to connect an `env-merge-info` event, to merge the `env.remote_images`: https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-merge-info

**Comment by t-b** [comment]
@chrisjsewell Thanks for fixing it properly!

**Comment by chrisjsewell** [comment]
no problem 😄
